[metadata]
name=llmage
version = 0.0.1
description = Your project description
author = "yu moqing"
author_email = "yumoqing@gmail.com"
readme = "README.md"
license = "MIT"
[options]
packages = find:
requires_python = ">=3.8"
install_requires = 
	xlrd
	bs4
	xlwt
	nanoid
	psutil
	ujson
	numpy
	rsa
	brotli
	aiohttp
	asyncio 
	aiohttp
	aiohttp_socks
	requests
	jinja2
	pyzmq
	cryptography
	bcrypt
	asyncssh
	eventpy

